version: 0.0
os: linux

files:
  - source: /
    destination: /home/ubuntu/oneit
    overwrite: yes
file_exists_behavior: OVERWRITE
permissions:
  - object: /home/ubuntu/oneit
    owner: ubuntu
    group: ubuntu
    mode: 755

hooks:
  ApplicationStop:
    - location: scripts/stop.sh
      timeout: 60
      runas: ubuntu
  BeforeInstall:
    - location: scripts/infisical.sh
      timeout: 60
      runas: ubuntu
  AfterInstall:
    - location: scripts/start.sh
      timeout: 60
      runas: ubuntu