spring:
  flyway:
    enabled: true
    url: jdbc:mysql://${DB_ENDPOINT}/${DATABASE_NAME}?serverTimezone=Asia/Seoul
    user: ${DB_USER}
    password: ${DB_PASSWORD}
    baseline-on-migrate: true
    locations: classpath:db/migration
    baseline-version: 1