server:
  port: 9000
  timezone: Asia/Seoul

spring:
  application:
    name: api
  request:
    url: ${REQUEST_URL}
  jpa:
    show-sql: false
    properties:
      hibernate:
        format_sql: true
        jdbc.time_zone: UTC
        jdbc:
          time_zone: Asia/Seoul
  cloud:
    aws:
      s3:
        bucket: ${AWS_S3_BUCKET_NAME}
      credentials:
        access-key: ${AWS_S3_ACCESS_KEY}
        secret-key: ${AWS_S3_SECRET_ACCESS_KEY}
      region:
        static: ${AWS_REGION}
      stack:
        auto: false

  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 10MB

cdn:
  domain: ${CDN_DOMAIN}

springdoc:
  swagger-ui:
    path: /api-swagger  # swagger-ui ?? ??
    groups-order: DESC
    tags-sorter: alpha
    operations-sorter: method
  paths-to-match:
    - /api/** # swagger-ui? ??? api? ????? ??

logging:
  level:
    org.springframework.boot.autoconfigure.logging: ERROR

webhook:
  slack:
    url: ${WEBHOOK_SLACK_URL}

fcm:
  config:
    path: firebase-admin-sdk.json
  base-url: https://fcm.googleapis.com/v1/projects/oneit-gpt/messages:send
  auth-url: https://www.googleapis.com/auth/cloud-platform

kakao:
  talk-dream:
    auth-token: ${KAKAO_ALARM_AUTH_TOKEN}
    server-name: ${KAKAO_ALARM_SERVER_NAME}
    service-id: ${KAKAO_ALARM_SERVICE_ID}
    customer-inquiry: ${KAKAO_ALARM_CUSTOMER_INQUIRY}

sentry:
  dsn: ${SENTRY_DSN}
  exception-resolver-order: -2147483647
  max-request-body-size: always
  send-default-pii: true
  traces-sample-rate: 1.0
