spring:
  application:
    name: batch
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/${LOCAL_DATABASE}?
    username: ${LOCAL_USER}
    password: ${LOCAL_PASSWORD}
  batch:
    datasource:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://localhost:3306/test_batch_meta?
      username: ${LOCAL_USER}
      password: ${LOCAL_PASSWORD}
    jdbc:
      initialize-schema: always

fcm:
  base-url: https://fcm.googleapis.com/v1/projects/oneit-gpt/messages:send
  auth-url: https://www.googleapis.com/auth/cloud-platform
  config:
    path: firebase-admin-sdk.json