name: Spring CI CD

on:
  push:
    branches: ["main"]

jobs:

  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    # jdk 17 설치
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
    
    # gradle 실행 권한 부여
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    
    # gradle 빌드
    - name: Build with Gradle
      uses: gradle/gradle-build-action@v2.6.0
      with:
        arguments: build
        
    # artifact 업로드
    - name: Upload build artifact
      uses: actions/upload-artifact@v2
      with:
        name: build-artifact # Artifact 이름 지정
        path: build/libs/oneit_server-0.0.1-SNAPSHOT.jar # 폴더 지정

  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
      # artifact 다운로드
      - name: Download build artifact
        uses: actions/download-artifact@v2
        with:
          name: build-artifact
          path: build/libs/
    
      # LIGHTSAIL 배포
      - name: Deploy to LIGHTSAIL
        env:
          RDS_ENDPOINT: "${{ secrets.RDS_ENDPOINT }}"
          RDS_USER: "${{ secrets.RDS_USER }}"
          RDS_PASSWORD: "${{ secrets.RDS_PASSWORD }}"
          DEV_DATABASE: "$ {{ secrets.DEV_DATABASE }}"
        run: |
          echo "${{ secrets.LIGHTSAIL_SSH_KEY }}" > private_key.pem
          chmod 600 private_key.pem
          scp -i private_key.pem -o StrictHostKeyChecking=no build/libs/oneit_server-0.0.1-SNAPSHOT.jar ${{ secrets.LIGHTSAIL_USERNAME }}@${{ secrets.LIGHTSAIL_HOST }}:/home/${{ secrets.LIGHTSAIL_USERNAME }}/oneit_server-0.0.1-SNAPSHOT.jar
          ssh -i private_key.pem -o StrictHostKeyChecking=no ${{ secrets.LIGHTSAIL_USERNAME }}@${{ secrets.LIGHTSAIL_HOST }} "pgrep java | xargs kill -9; nohup java -jar /home/${{ secrets.LIGHTSAIL_USERNAME }}/oneit_server-0.0.1-SNAPSHOT.jar > app.log 2>&1 &"
          rm -f private_key.pem
